### ISSUE TITLE
File does not get updated

### ISSUE THREAD

**Issue by jLynx** [rfennell/JSONFileVersioner#2]
Hi So I am brand new to GitHub Actions, so please forgive me if I am missing a simple step.

I have created my yml file
```
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Apply Version to JSON file
      uses: rfennell/JSONFileVersioner@v1
      with:
        path: 'testdata'
        field: 'version'
        VersionNumber: '1.2.3'
        filenamepattern: '.json' 
        recursion: 'true'

```

And I have my folder structure as:
root>testdata>version.json

Inside that json file I have

```
{
"version": 1.1.1
}
```

I get no errors when it runs, but once it it completed the version is still 1.1.1

Am I missing a step here?

**Comment by rfennell** [comment]
To test this action I use a separate repo [ActionPlayround - which has an CI action](https://github.com/rfennell/ActionPlayground/blob/master/.github/workflows/nodejs.yml). This contains the fragment

```
 - uses: rfennell/JSONFileVersioner@v1
      with:
        path: 'testdata'
        field: 'version'
        VersionNumber: '1.2.3'
        filenamepattern: '.json' 
        recursion: 'true'
```

Remember the action does not update the version stored in the GitHub repo, but the version on the build agent. So only the built exe/dll/package will have the version number.

With the GitHub hosted agent this is hard to see, but as they have just release [self-hosted agents](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/hosting-your-own-runners) you should be able see the file on the agent changed.

I have been meaning to give self-hosted a try, so I will look too
