### ISSUE TITLE
##[error]Source directory does not exist: /home/runner/work/xo/xo/testdata

### ISSUE THREAD

**Issue by kpoxo6op** [rfennell/JSONFileVersioner#4]
trying this action on https://github.com/kpoxo6op/xo

getting the error below:
Set up job
1s
Run rfennell/JSONFileVersioner@v1
0s
##[error]Node run failed with exit code 1
Run rfennell/JSONFileVersioner@v1
##[error]Source directory does not exist: /home/runner/work/xo/xo/testdata
##[error]Node run failed with exit code 1
Complete job

**Comment by kpoxo6op** [comment]
my action:
```
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: rfennell/JSONFileVersioner@v1
      with:
        path: 'testdata'
        field: label
        VersionNumber: '1.0.0'
        filenamepatter: '.json'
        recursion: 'true'
```

**Comment by rfennell** [comment]
Looks like too many /XO's in the path. Not sure why, I will have to have a look at it

**Comment by rfennell** [comment]
The issue is that my task  update the local copy of the file on the build agent. It does not touch the actual GitHub hosted repo.

This means for it to work the agent must Checkout (i.e. clone the repo) locally before running my task. You do this by adding the checkout task

```
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: rfennell/JSONFileVersioner@v1
      with:
        path: 'testdata'
        field: label
        VersionNumber: '1.0.0'
        filenamepatter: '.json'
        recursion: 'true'
```

I will send the same fix as a PR
