### ISSUE TITLE
json file is not updated

### ISSUE THREAD

**Issue by kpoxo6op** [rfennell/JSONFileVersioner#5]
Thanks for helping me with the error in my first issue. The action is not throwing errors now however my `Requirements.json` file is not updated.

Maybe I don't understand actions at all... How is the updated Requirements.json going to get back into my master branch? I don't know... 

Anyways, expected action result:
`testdata/Requirements.json` version value is changed to "1.0.0".
```
{
  "version": "1.0.0"
}
```
Actual result:
testdata/Requirements.json is not updated.
```
{
  "version": "update-me"
}
```

repo:
https://github.com/kpoxo6op/xo
action:
```
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: rfennell/JSONFileVersioner@v1
      with:
        path: 'testdata'
        field: version
        VersionNumber: '1.0.0'
        filenamepattern: '.json'
        recursion: 'true'
```

action log attached
[logs_24.zip](https://github.com/rfennell/JSONFileVersioner/files/4074568/logs_24.zip)
